sudo: false

language: node_js
node_js:
  - 8

before_install:
  - npm install codecov.io coveralls

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - integration
    - master

provider: pages
  skip_cleanup: true
  github_token: $github_token  # Set in the settings page of your repository in the travis ci
  keep_history: true
  local_dir: styleguide
  on:
    branch: master
