sudo: false

language: node_js
node_js:
  - 8

before_install:
  - npm install codecov.io

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js

branches:
  only:
    - integration
    - master
    - gh-pages
    - /(\d+\.)?(\d+\.)?(\*|\d+)/ # for tags

before_deploy:
    - npm install
    - npm run-script build

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: public
    on:
        branch: master
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
        tags: true