sudo: false

language: node_js
node_js:
  - 8

before_install:
  - npm install codecov.io

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js

branches:
  only:
    - integration
    - master
    - gh-pages
    - /^(\d+\.)?(\d+\.)?(\*|\d+)$/ # for tags

deploy:
  - provider: script
    script: npm run-script build
    on:
        branch: master
  - provider: script
    script: npm install
    on:
        condition: branch =~ /^(\d+\.)?(\d+\.)?(\*|\d+)$/ # for tags
    local_dir: public
    on:
        branch: master
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
        tags: true